### ISSUE TITLE
Unimplemented 'Color' and 'File' buttons in 'Edit input' dialog

### ISSUE THREAD

**Issue by csyshing** [luisbarrancos/shrimp#2]
Reproduce steps:
1. Click 'Add Block' button
2. Add "Shader Functions" -> "Diffuse" -> "Diffuse"
3. Right click "Cdiff" input in newly created "Diffuse" block, click "Edit"
4. Clicking 'Color' and 'File' buttons in popup dialog do nothing

**Comment by luisbarrancos** [comment]
Done with 98f3533a65722e4fd706a20201ee13997dd52732, thanks for the PR 👍
